# Config options
markdown: kramdown
sass:
  style: :compressed
  sass_dir: _sass
permalink: /posts/:title/
gems:
  - jekyll-redirect-from
  - jekyll-feed
timezone: America/New_York

# Site-level data
name: Merkurev Viktor
keywords:
  - developer
  - cryptography
  - Python / ABAP
description: ""
excerpt_separator: <!--more-->
